#ifndef CONTROL_IDS_H_INCLUDED
#define CONTROL_IDS_H_INCLUDED 42

#define FILE_TESTBUTTON 4201
#define FILE_EXIT 4202
#define FILE_FLASHWINDOW 4203
#define MENU_TEST 4204

#endif // CONTROL_IDS_H_INCLUDED
